name: BetterMending
main: io.github.paulem.btm.BetterMending
version: 2.6.4.2
website: paulem79.github.io
author: Paulem
description: A small quality of life tweak to the Mending enchantment
api-version: 1.13

commands:
  btm:
    usage: /btm [toggle, version]
    description: Enable or disable the Mending skill
    permission: btm.commands.btm
    aliases:
      - betterthanmending

permissions:
  btm.commands.btm:
    description: Control the command /btm used to enable or disable the Mending skill
    default: true
  btm.use:
    description: Allows to use the mending ability
    default: true